name: CMake on a single platform

on:
  push:
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:

    - uses: actions/checkout@v4

    - name: Install Deps
      run: |
        sudo apt-get update
        sudo apt install -y ninja qtbase6-dev cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} -VV

