name: build test and lint

on:
  push:
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:

    - uses: actions/checkout@v4

    - name: Install Deps
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libgl1-mesa-dev
        sudo apt install -y xorg-server qt6-base-dev qt6-base-private-dev qt6-declarative-dev qt6-declarative-private-dev qt6-tools-dev qt6-tools-private-dev qt6-scxml-dev qt6-documentation-tools libqt6core5compat6-dev qt6-tools-dev-tools qt6-l10n-tools qt6-shader-baker libqt6shadertools6-dev qt6-quick3d-dev qt6-quick3d-dev-tools libqt6svg6-dev libqt6quicktimeline6-dev libqt6serialport6-dev 
        sudo apt install -y ninja-build clang cmake

    - name: Configure CMake
      run: |
        cmake . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tests/TestComponents
