name: build test and lint

on:
  push:
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:

    - uses: actions/checkout@v4

    - name: Install Deps
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libgl1-mesa-dev
        sudo apt install -y qt6-base-dev qt6-base-dev-tools qt6-base-private-dev ninja-build clang cmake

    - name: Configure CMake
      run: |
        cmake . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tests/TestComponents

